import { Order } from '../../types';
import { calculateSettlement } from '../../services/settlementService';

export const INITIAL_SEED_ORDERS: Omit<Order, 'id' | 'orderNo' | 'createdAt' | 'updatedAt' | 'actualAmount' | 'platformFee' | 'transferAmount'>[] = [
  /* ============ 普通订单（standard） ============ */
  {
    type: 'standard',
    customerName: '甘雨厨喵',
    customerPhone: '13812345678',
    project: '深渊 12 层满星通关 (9★)',
    amount: 68.0,
    server: 'official',
    platform: 'xianyu',
    remark: '客户练度不错，队伍配齐草行久和万达国际',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '可莉小太阳',
    customerPhone: '18600112233',
    project: '须弥沙漠全锚点及沙漠遗迹 100%',
    amount: 150.0,
    server: 'bilibili',
    platform: 'xianyu',
    remark: '已转单给打手阿木，抽成20%，需在周三前交单',
    isTransferred: true,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '夜兰真爱粉',
    customerPhone: '17766554433',
    project: '混沌回忆 12 层满星攻坚',
    amount: 50.0,
    server: 'official',
    platform: 'wechat',
    remark: '已顺利通关并发送截图给客户好评',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '绝区零治安官',
    customerPhone: '13399887766',
    project: '式舆防卫战剧变节点 6 层',
    amount: 88.0,
    server: 'international',
    platform: 'xianyu',
    remark: '朱鸢主C，驱动盘配装完成',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '鸣潮漂泊者',
    customerPhone: '18955443322',
    project: '深坠异想奇境难度5通关',
    amount: 60.0,
    server: 'international',
    platform: 'wechat',
    remark: '转单给小林代打，保留声骸强化截图',
    isTransferred: true,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '星穹开拓者',
    customerPhone: '13911223344',
    project: '差分宇宙协议6通关与成就收集',
    amount: 45.0,
    server: 'official',
    platform: 'xianyu',
    remark: '客户中途自行通关，友好协商退单',
    isTransferred: false,
    status: 'cancelled',
  },
  {
    type: 'standard',
    customerName: '刻晴大小姐',
    customerPhone: '13700001122',
    project: '雷神周本+草龙周本全材料速刷',
    amount: 25.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '长期老客户，赠送下周天赋本材料清理',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '钟离钱包喵',
    customerPhone: '15012345678',
    project: '枫丹水下遗迹与隐藏锚点全收集',
    amount: 120.0,
    server: 'official',
    platform: 'xianyu',
    remark: '优先做声望委托，宝箱顺路开',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '纳西妲信徒',
    customerPhone: '15298765432',
    project: '须弥雨林宝箱+任务 100% 全清',
    amount: 95.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '转单给打手糖糖，需要提交探索度截图',
    isTransferred: true,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '芙宁娜单推人',
    customerPhone: '15877778888',
    project: '厄里那斯+海露港 探索度补满',
    amount: 80.0,
    server: 'official',
    platform: 'xianyu',
    remark: '歌剧院周边锚点优先解锁',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '温迪吟游诗人',
    customerPhone: '13644445555',
    project: '蒙德每日委托代做 (7天)',
    amount: 49.0,
    server: 'official',
    platform: 'wechat',
    remark: '顺手清掉风起地神瞳',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '阿蕾奇诺厨',
    customerPhone: '13555556666',
    project: '仆人周本材料速刷 (40次)',
    amount: 66.0,
    server: 'bilibili',
    platform: 'xianyu',
    remark: '已转单给打手老黄，产出截图留档',
    isTransferred: true,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '神里绫华控',
    customerPhone: '18822223333',
    project: '稻妻清籁岛全宝箱收集',
    amount: 72.0,
    server: 'official',
    platform: 'wechat',
    remark: '雷音权现先不打，客户要自己打',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '胡桃冲鸭',
    customerPhone: '13788889999',
    project: '璃月层岩巨渊深层探索',
    amount: 90.0,
    server: 'official',
    platform: 'xianyu',
    remark: '流明石升级到10级后再下深层',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '雷电将军大人',
    customerPhone: '13966667777',
    project: '鸣神大社+镇守之森任务全清',
    amount: 58.0,
    server: 'bilibili',
    platform: 'xianyu',
    remark: '神樱大祓任务线较长，分两次交单',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '开拓者一枚',
    customerPhone: '18677778888',
    project: '匹诺康尼地图探索 100%',
    amount: 130.0,
    server: 'official',
    platform: 'wechat',
    remark: '转单给打手小周，梦幻酒店区域最后做',
    isTransferred: true,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '花火大小姐',
    customerPhone: '13344445555',
    project: '模拟宇宙黄金与机械 全部隐藏成就',
    amount: 110.0,
    server: 'international',
    platform: 'xianyu',
    remark: '需要解锁全部命途回响',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '真理医生粉',
    customerPhone: '15933332222',
    project: '战意奔涌 0 回合速通挑战',
    amount: 75.0,
    server: 'official',
    platform: 'wechat',
    remark: '配队真理医生+托帕+知更鸟，一把过',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '知更鸟歌迷',
    customerPhone: '18899990000',
    project: '匹诺康尼钟表把戏全任务',
    amount: 55.0,
    server: 'official',
    platform: 'xianyu',
    remark: '梦境护照图鉴顺便集齐',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '邦布驾驶员',
    customerPhone: '13566667777',
    project: '零号空洞 全委托通关',
    amount: 85.0,
    server: 'international',
    platform: 'xianyu',
    remark: '转单给打手阿珂，鸣徽收集优先',
    isTransferred: true,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '星见雅粉丝',
    customerPhone: '15822223333',
    project: '防卫战第十层全满星',
    amount: 98.0,
    server: 'official',
    platform: 'wechat',
    remark: '上下半间都要3星，争取一次完成',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '格莉丝姐',
    customerPhone: '13988887777',
    project: '录像店经营日常代管 (14天)',
    amount: 120.0,
    server: 'official',
    platform: 'xianyu',
    remark: '客源宣传单每日必做',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '明日方舟刀客塔',
    customerPhone: '13699998888',
    project: '危机合约 18 级全奖励',
    amount: 100.0,
    server: 'official',
    platform: 'xianyu',
    remark: '词条组合按高难推荐来，尽量日替全清',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '博士本博',
    customerPhone: '13322224444',
    project: '剿灭作战代理全清',
    amount: 40.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '三个剿灭本挂机代理即可',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '斯卡蒂老婆',
    customerPhone: '13755556666',
    project: '生息演算全结局通关',
    amount: 150.0,
    server: 'official',
    platform: 'xianyu',
    remark: '转单给打手墨白，需要录屏交单',
    isTransferred: true,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '阿米娅会长',
    customerPhone: '18844445555',
    project: '新主线剧情全通 + 材料刷取',
    amount: 70.0,
    server: 'official',
    platform: 'wechat',
    remark: '主线关卡+材料本一起处理',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'standard',
    customerName: '崩坏3舰长',
    customerPhone: '15911112222',
    project: '乐土终章 100% 通关',
    amount: 65.0,
    server: 'official',
    platform: 'xianyu',
    remark: '刻印选螺旋+繁星，稳定通关',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '琪亚娜天下第一',
    customerPhone: '13577778888',
    project: '深渊红莲保级 (2期)',
    amount: 92.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '每期结算日前一晚开打，注意天气',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'standard',
    customerName: '布洛妮娅厨',
    customerPhone: '13855556666',
    project: '往世乐土英桀任务全清',
    amount: 78.0,
    server: 'international',
    platform: 'xianyu',
    remark: '全英桀对话CG要截图留档',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'standard',
    customerName: '幻塔开拓者',
    customerPhone: '13644449999',
    project: '维拉地图全探索 100%',
    amount: 110.0,
    server: 'official',
    platform: 'wechat',
    remark: '转单给打手阿城，灰域BOSS顺手打',
    isTransferred: true,
    status: 'pending',
  },

  /* ============ 托管订单（hosting） ============ */
  {
    type: 'hosting',
    customerName: '流萤单推人',
    customerPhone: '15988776655',
    project: '星穹铁道日常体力代清 (30天)',
    amount: 198.0,
    server: 'official',
    platform: 'wechat',
    remark: '早晚各清一次体力，遗器刷出攻击套留着',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '提瓦特旅行者',
    customerPhone: '13566778899',
    project: '原神枫丹主线与世界任务全清',
    amount: 120.0,
    server: 'official',
    platform: 'xianyu',
    remark: '任务已推进到水仙十字院',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'hosting',
    customerName: '原神月卡战士',
    customerPhone: '13822223333',
    project: '原神每日委托+体力 全勤代管 (90天)',
    amount: 520.0,
    server: 'official',
    platform: 'xianyu',
    remark: '树脂优先刷绝缘本，圣遗物按词条留',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '崩铁全勤党',
    customerPhone: '15966667777',
    project: '星穹铁道每日委托+模拟宇宙 (30天)',
    amount: 260.0,
    server: 'official',
    platform: 'wechat',
    remark: '每周模拟宇宙奖励拿满，周本必打',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'hosting',
    customerName: '绝区零邦布',
    customerPhone: '13377778888',
    project: '绝区零日常+录像店代管 (30天)',
    amount: 240.0,
    server: 'official',
    platform: 'xianyu',
    remark: '转单给打手小七，邦布芯片每日必清',
    isTransferred: true,
    status: 'pending',
  },
  {
    type: 'hosting',
    customerName: '明日方舟常驻',
    customerPhone: '18633334444',
    project: '明日方舟每日基建+剿灭 (60天)',
    amount: 300.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '基建排班按金条优先，公招用4星保底',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '尘白禁区玩家',
    customerPhone: '13722223333',
    project: '尘白禁区每日任务代清 (30天)',
    amount: 210.0,
    server: 'official',
    platform: 'xianyu',
    remark: '联机任务每日做满，剧情快进即可',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'hosting',
    customerName: '鸣潮深潜者',
    customerPhone: '13944445555',
    project: '鸣潮每日声骸+体力 (30天)',
    amount: 230.0,
    server: 'official',
    platform: 'wechat',
    remark: '转单给打手阿铭，声骸按词条筛选截图',
    isTransferred: true,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '碧蓝指挥官',
    customerPhone: '18855556666',
    project: '碧蓝航线每日委托+大世界 (60天)',
    amount: 280.0,
    server: 'official',
    platform: 'xianyu',
    remark: '大世界月度BOSS记得打，石油别溢出',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'hosting',
    customerName: '崩3资深舰长',
    customerPhone: '13588889999',
    project: '崩坏3每日清体+深渊 (30天)',
    amount: 220.0,
    server: 'bilibili',
    platform: 'wechat',
    remark: '深渊按红莲目标打，周末结算注意时间',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'hosting',
    customerName: '梦幻老玩家',
    customerPhone: '15844445555',
    project: '梦幻西游师门+押镖代跑 (90天)',
    amount: 680.0,
    server: 'official',
    platform: 'xianyu',
    remark: '转单给打手阿龙，押镖只跑大唐境外线',
    isTransferred: true,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '王者荣耀上分',
    customerPhone: '13366667777',
    project: '王者荣耀每日任务+战令 (30天)',
    amount: 250.0,
    server: 'official',
    platform: 'wechat',
    remark: '排位只打王者段以下，战令任务全清',
    isTransferred: false,
    status: 'pending',
  },
  {
    type: 'hosting',
    customerName: '剑网三侠士',
    customerPhone: '13799990000',
    project: '剑网3日常茶馆+大战 (30天)',
    amount: 320.0,
    server: 'international',
    platform: 'xianyu',
    remark: '威望上限别浪费，大战随缘跟车',
    isTransferred: false,
    status: 'in_progress',
  },
  {
    type: 'hosting',
    customerName: '暖暖玩家',
    customerPhone: '18655556666',
    project: '无限暖暖每日体力+时尚赛 (30天)',
    amount: 200.0,
    server: 'official',
    platform: 'wechat',
    remark: '时尚赛按客户提供的套装方案提交',
    isTransferred: false,
    status: 'completed',
  },
  {
    type: 'hosting',
    customerName: '燕云侠客',
    customerPhone: '15922223333',
    project: '燕云十六声每日任务代清 (30天)',
    amount: 270.0,
    server: 'official',
    platform: 'xianyu',
    remark: '转单给打手阿泽，奇术修炼每日做满',
    isTransferred: true,
    status: 'pending',
  },
];

export function generateSeedOrders(): Order[] {
  const baseTime = Date.now();

  return INITIAL_SEED_ORDERS.map((item, index) => {
    const timestamp = new Date(baseTime - index * 3600 * 1000 * 5).toISOString();
    const dateObj = new Date(baseTime - index * 3600 * 1000 * 5);
    const yy = String(dateObj.getFullYear()).slice(-2);
    const mm = String(dateObj.getMonth() + 1).padStart(2, '0');
    const dd = String(dateObj.getDate()).padStart(2, '0');
    const seq = String(index + 1).padStart(2, '0');
    const orderNo = `#NTE${yy}${mm}${dd}${seq}`;
    const id = `seed_order_${index + 1}`;

    const settlement = calculateSettlement({
      type: item.type,
      amount: item.amount,
      isTransferred: item.isTransferred,
      platform: item.platform,
    });

    return {
      ...item,
      id,
      orderNo,
      transferAmount: settlement.transferAmount,
      platformFee: settlement.platformFee,
      actualAmount: settlement.actualAmount,
      createdAt: timestamp,
      updatedAt: timestamp,
    };
  });
}
